### ISSUE TITLE
Gulp runner not working

### ISSUE THREAD

**Issue by impworks** [jonnyzzz/TeamCity.Node#64] opened 2015-01-13 11:38 UTC
Hello,

I'm having some troubles running a Gulp build. My build steps are as follows:

1. Install NPM Modules (default settings, install & test commands)
2. Build Gulp (NPM package from project)

The packages are installed, but then the Gulp step fails with:

```
Failed to find gulp.cmd under C:\TeamCity\buildAgent\work\e8ecf9a43bcdba79.
Please install 'gulp' as project-local Node.js NPM package
```

Gulp is definitely mentioned in my `package.json` file; it gets downloaded and installed. However, the `gulp.cmd` is found not the root of the project, but in the `\node_modules\.bin\` subdirectory. I tried changing the working dir property to that path, but the error still exists.

Tried using "System-wide Gulp" setting, but couldn't make it work either - the agent becomes uncompatible:

```
Unmet requirements: gulp exists
```

Installing Gulp via `npm install -g gulp` has no effect on the message, and neither does restarting the agent / server work.

My system is:
* Windows: 8.1 Pro x64
* TeamCity: 9.0 (build 32060)
* NodeJS Build Runner: 1.0.58
* Node.JS: 0.10.35

What am I doing wrong?

**Comment by jonnyzzz** [comment] 2015-01-13 11:58
I'll check the first issue.
To have global gulp reported you need to restart build agent

Best regards,
Eugene Petrenko

**Comment by impworks** [comment] 2015-01-13 12:07
I restarted the agent, then the server, then the agent yet again. Gulp's presense is still undetected.

**Comment by jonnyzzz** [comment] 2015-01-13 12:29
Please check agent logs. There must be information on gulp detection
failure. Have you installed gulp for the same user account as used to run
the agent?

**Comment by impworks** [comment] 2015-01-13 12:38
Yeah, this was probably the cause. I installed Node.JS from my own account and it only modified the user's PATH environment variable, which was not available to TeamCity Agent. I added the path to NPM to global PATH variable and the agent started detecting Gulp. Thanks!

**Comment by jonnyzzz** [comment] 2015-03-29 14:20
Glad to read the issue is resolved. Closing it now.

**Closed by jonnyzzz** 2015-03-29 14:20 UTC

**Comment by Myster** [comment] 2016-03-28 21:54
NB: I had the same symptom, because we'd missed the 'Working Directory' setting in the task runner (hidden under advanced options)
